### ISSUE TITLE
BOM link not working

### ISSUE THREAD

**Issue by warrenstanley** [pmandes/zx-spectrum-issue6a-replica#2]
Hi - just a heads up, I seem to be having issues 8bit.yarek.pl. Tried using:

Microsoft Edge
Version 121.0.2220.3 (Official build) dev (64-bit)
Google Chrome
Version 119.0.6045.200 (Official Build) (64-bit)

The domains are probably outside your control, do you additional alternative sources?

**Comment by pmandes** [comment]
It looks like Yarek's website is down.
You can find information about how it works
and how to make the ZX8401 (as well as all the files necessary for production) here:
https://trastero.speccy.org/cosas/JL/pcf1306p/PCF1306P.html

**Comment by warrenstanley** [comment]
Awesome - thanks Paweł
